### ISSUE TITLE
i am not able to use NetRipper 

### ISSUE THREAD

**Issue by activenew** [NytroRST/NetRipper#8]
Hi All,
This first post for me , i am also very new in this field, i am facing issue with NetRipper ,i used the below steps to add Netripper module to metasploit.

mkdir /usr/share/metasploit-framework/modules/post/windows/gather/netripper
cp netripper.rb /usr/share/metasploit-framework/modules/post/windows/gather/netripper.rb
g++ -Wall netripper.cpp -o netripper
cp netripper /usr/share/metasploit-framework/modules/post/windows/gather/netripper/netripper
cd ../Release
cp DLL.dll /usr/share/metasploit-framework/modules/post/windows/gather/netripper/DLL.dll
its appear with module but i can't select it.

Note:i did not found (Release folder) after download the module, so i made it manually and added (DLL.dll) file on it

Also had copied in the following path but the same problem i am unable to use it
opt/metasploit-framework/embedded/framework/modules/post/windows/gather

please advise me.

**Comment by NytroRST** [comment]
Hi,
Thank you for reminding me about this issue. When I upgraded to x64 support, there are two versions, x86 and x64. I will have to rewrite the metasploit module and I will do it when I will have some free time. 

Until then, instead of "cd ../Release" you can "cd ../Win32" and it should work. I will also update the README file.
Thanks!

**Comment by activenew** [comment]
thank you for reply
already did cd ../Win32  but not work.
How to remove it completely? You have installed it more than 2 times. This is probably the cause of the problem.

please advise me.

**Comment by NytroRST** [comment]
To remove it, you need to remove the files you created: 
rm -f netripper 
rm -f /usr/share/metasploit-framework/modules/post/windows/gather/netripper.rb
rm -f /usr/share/metasploit-framework/modules/post/windows/gather/netripper/netripper
rm -f /usr/share/metasploit-framework/modules/post/windows/gather/netripper/DLL.dll
rm -rf /usr/share/metasploit-framework/modules/post/windows/gather/netripper

In order to install it, download the contents from the "Metasploit" directory and follow the steps. It should work. Also, I think there are some videos with the installation on Youtube, or at least some articles, just use Google to find them.

**Comment by activenew** [comment]
I must to run this command every time in order to able use netripper
msf> Loadpath /usr/share/metasploit-framework/modules/
after run the command i can use it , when inject process it done successfully no error but i can't find logs on victim machine

I tried inject both (explorer and chrome) same result.
any advise please.

**Comment by NytroRST** [comment]
Chrome should work only on x64. Try firefox, it should work.
You can find the data in C:\Users\[UserName]\AppData\Local\Temp\NetRipper

**Comment by activenew** [comment]
yes chrome on windows 7 x64, but i cant not find Netripper folder in this location

Thanks for reply

**Comment by NytroRST** [comment]
Which folder in the location I specified you cannot find?

**Comment by activenew** [comment]
I mean Netripper Folder i cannot find it, also i tried with Firefox same result

**Comment by NytroRST** [comment]
First command, the above one, will create it: 

mkdir /usr/share/metasploit-framework/modules/post/windows/gather/netripper

Do you use Kali Linux, right?

**Comment by NytroRST** [comment]
Oh, I understand. Did you configure any option before running netripper module? 

NetRipper will get Temp folder using WinAPI. It might also be here: C:\Users\NAME\AppData\Local\Roaming\Temp . Try tonfind Roamnig folder and search there.

Which OS do you target? If it is XP, it will be other path.

**Comment by activenew** [comment]
i am use kali linux correct.
Which OS do you target? Win7 x64

i will search in romaing folder and will feedback

**Comment by activenew** [comment]
i tried to inject firefox.exe again but the same. Netripper folder not available  in local or roaming .
something went wrong in my machine
please check screenshot in attachment if something missing or i did wrong .
![netripper](https://user-images.githubusercontent.com/31375398/31143074-ce69481e-a884-11e7-992b-98b1a02e46a7.jpg)

**Comment by NytroRST** [comment]
From what I remember, it should be a “successfully injected” message. Is the firefox process x64 and NerRipper x86?

**Comment by activenew** [comment]
firefox 32bit, but i don't know about netripper , how can i check netripper version ?

sorry for that , please be patient i am new in this field.

**Comment by NytroRST** [comment]
No problem, I try to help you. Until a recent release, NetRipper had only 32bit support. Now it has also 64bit support.

Here, you can find two folders:
1. For 32bit: https://github.com/NytroRST/NetRipper/tree/master/Win32
2. For 64bit: https://github.com/NytroRST/NetRipper/tree/master/x64

Both folders have a file called "DLL.dll", the DLL that will be injected in Firefox or other processes. 

The Metasploit module, needs to have one of the DLLs here: /usr/share/metasploit-framework/modules/post/windows/gather/netripper/DLL.dll so if the target process is 32 bit, just copy the DLL from the 32bit location to that path and run the module.

Also, in order to find the path (NetRipper), you will need to find the "Temporary folder" from the user running the target process. If the process is executed by a different user, it will probably not work to inject the DLL. If you have access to that system, try to open a CMD as Administrator, and run the following command: NetRipper.exe DLL.dll firefox.exe. From Metasploit, you will need to escalate privileges (getsystem?) in this case.

Can you check the user running the firefox process (ps) and the current user (whoami)?

**Comment by activenew** [comment]
Thanks a lot for explanation 
I'll do this, then I'll let you know.

thank you for support
